# Have the operator create and own a dedicated ServiceAccount for the
# scheduler, and point the worker pool at a ServiceAccount that already
# exists (created by Helm, another operator, or a human) instead.
apiVersion: compute.pola.rs/v1alpha1
kind: PolarsCluster
metadata:
  name: polars-serviceaccount
spec:
  acceptEula: true
  license:
    onPremEnterprise:
      secretName: license
      secretProperty: license.json
  runtime:
    composed: {}
  scheduler:
    serviceAccount:
      create: true
  workerPool:
    replicas: 2
    serviceAccount:
      name: my-existing-worker-sa
