apiVersion: compute.pola.rs/v1alpha1
kind: PolarsCluster
metadata:
  labels:
    app.kubernetes.io/name: polars-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: polars
spec:
  acceptEula: true
  license:
    onPremEnterprise:
      # Create this Secret from your Polars on-premises enterprise license:
      #   kubectl create secret generic license --from-file=license.json=<path to license>
      secretName: license
      secretProperty: license.json
  runtime:
    composed:
      dist:
        repository: polars-on-premises
        tag: "latest"
        pullPolicy: IfNotPresent
  workerPool:
    replicas: 2
