apiVersion: compute.pola.rs/v1
kind: PolarsCluster
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: polars
spec:
  acceptEula: true
  # Version of Polars on-premises to run. Used as the dist image tag unless
  # runtime.composed.dist.tag overrides it.
  version: "latest"
  license:
    licenseServer:
      uri: https://license-server.default:50051
  runtime:
    composed:
      dist:
        repository: polars-on-premises
        pullPolicy: IfNotPresent
  workerPool:
    podTemplate:
      spec:
        containers:
          - name: worker
            resources:
              limits:
                cpu: 1
    minReplicas: 0
    maxReplicas: 3
    replicas: 0
