//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousResultsABSSpec) DeepCopyInto(out *AnonymousResultsABSSpec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousResultsABSSpec.
func (in *AnonymousResultsABSSpec) DeepCopy() *AnonymousResultsABSSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousResultsABSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousResultsGCSSpec) DeepCopyInto(out *AnonymousResultsGCSSpec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousResultsGCSSpec.
func (in *AnonymousResultsGCSSpec) DeepCopy() *AnonymousResultsGCSSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousResultsGCSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousResultsS3Spec) DeepCopyInto(out *AnonymousResultsS3Spec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousResultsS3Spec.
func (in *AnonymousResultsS3Spec) DeepCopy() *AnonymousResultsS3Spec {
	if in == nil {
		return nil
	}
	out := new(AnonymousResultsS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousResultsSpec) DeepCopyInto(out *AnonymousResultsSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(AnonymousResultsS3Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.ABS != nil {
		in, out := &in.ABS, &out.ABS
		*out = new(AnonymousResultsABSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(AnonymousResultsGCSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(SharedFilesystemSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousResultsSpec.
func (in *AnonymousResultsSpec) DeepCopy() *AnonymousResultsSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousResultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointABSSpec) DeepCopyInto(out *CheckpointABSSpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointABSSpec.
func (in *CheckpointABSSpec) DeepCopy() *CheckpointABSSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointABSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointDataSpec) DeepCopyInto(out *CheckpointDataSpec) {
	*out = *in
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(SharedFilesystemSpec)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(CheckpointS3Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.ABS != nil {
		in, out := &in.ABS, &out.ABS
		*out = new(CheckpointABSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(CheckpointGCSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointDataSpec.
func (in *CheckpointDataSpec) DeepCopy() *CheckpointDataSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointGCSSpec) DeepCopyInto(out *CheckpointGCSSpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointGCSSpec.
func (in *CheckpointGCSSpec) DeepCopy() *CheckpointGCSSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointGCSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointS3Spec) DeepCopyInto(out *CheckpointS3Spec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointS3Spec.
func (in *CheckpointS3Spec) DeepCopy() *CheckpointS3Spec {
	if in == nil {
		return nil
	}
	out := new(CheckpointS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointSpec) DeepCopyInto(out *CheckpointSpec) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(metav1.Duration)
		**out = **in
	}
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointSpec.
func (in *CheckpointSpec) DeepCopy() *CheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposedRuntimeSpec) DeepCopyInto(out *ComposedRuntimeSpec) {
	*out = *in
	if in.Dist != nil {
		in, out := &in.Dist, &out.Dist
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposedRuntimeSpec.
func (in *ComposedRuntimeSpec) DeepCopy() *ComposedRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(ComposedRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralVolumeClaimSpec) DeepCopyInto(out *EphemeralVolumeClaimSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralVolumeClaimSpec.
func (in *EphemeralVolumeClaimSpec) DeepCopy() *EphemeralVolumeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralVolumeClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMetricsSpec) DeepCopyInto(out *HostMetricsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMetricsSpec.
func (in *HostMetricsSpec) DeepCopy() *HostMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(HostMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseOnPremEnterpriseSpec) DeepCopyInto(out *LicenseOnPremEnterpriseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseOnPremEnterpriseSpec.
func (in *LicenseOnPremEnterpriseSpec) DeepCopy() *LicenseOnPremEnterpriseSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseOnPremEnterpriseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseOnPremSpec) DeepCopyInto(out *LicenseOnPremSpec) {
	*out = *in
	in.ClientID.DeepCopyInto(&out.ClientID)
	in.ClientSecret.DeepCopyInto(&out.ClientSecret)
	in.WorkspaceID.DeepCopyInto(&out.WorkspaceID)
	if in.LicenseData != nil {
		in, out := &in.LicenseData, &out.LicenseData
		*out = new(PersistentVolumeClaimRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseOnPremSpec.
func (in *LicenseOnPremSpec) DeepCopy() *LicenseOnPremSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseOnPremSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSpec) DeepCopyInto(out *LicenseSpec) {
	*out = *in
	if in.OnPrem != nil {
		in, out := &in.OnPrem, &out.OnPrem
		*out = new(LicenseOnPremSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OnPremEnterprise != nil {
		in, out := &in.OnPremEnterprise, &out.OnPremEnterprise
		*out = new(LicenseOnPremEnterpriseSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSpec.
func (in *LicenseSpec) DeepCopy() *LicenseSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageSpec) DeepCopyInto(out *LineageSpec) {
	*out = *in
	in.Transport.DeepCopyInto(&out.Transport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageSpec.
func (in *LineageSpec) DeepCopy() *LineageSpec {
	if in == nil {
		return nil
	}
	out := new(LineageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageTransportHTTPSpec) DeepCopyInto(out *LineageTransportHTTPSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageTransportHTTPSpec.
func (in *LineageTransportHTTPSpec) DeepCopy() *LineageTransportHTTPSpec {
	if in == nil {
		return nil
	}
	out := new(LineageTransportHTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageTransportSpec) DeepCopyInto(out *LineageTransportSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(LineageTransportHTTPSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageTransportSpec.
func (in *LineageTransportSpec) DeepCopy() *LineageTransportSpec {
	if in == nil {
		return nil
	}
	out := new(LineageTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalFilesystemSpec) DeepCopyInto(out *LocalFilesystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalFilesystemSpec.
func (in *LocalFilesystemSpec) DeepCopy() *LocalFilesystemSpec {
	if in == nil {
		return nil
	}
	out := new(LocalFilesystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservatorySpec) DeepCopyInto(out *ObservatorySpec) {
	*out = *in
	if in.PersistentVolumeClaim != nil {
		in, out := &in.PersistentVolumeClaim, &out.PersistentVolumeClaim
		*out = new(PersistentVolumeClaimRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservatorySpec.
func (in *ObservatorySpec) DeepCopy() *ObservatorySpec {
	if in == nil {
		return nil
	}
	out := new(ObservatorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimRef) DeepCopyInto(out *PersistentVolumeClaimRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimRef.
func (in *PersistentVolumeClaimRef) DeepCopy() *PersistentVolumeClaimRef {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarsCluster) DeepCopyInto(out *PolarsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarsCluster.
func (in *PolarsCluster) DeepCopy() *PolarsCluster {
	if in == nil {
		return nil
	}
	out := new(PolarsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarsClusterList) DeepCopyInto(out *PolarsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarsClusterList.
func (in *PolarsClusterList) DeepCopy() *PolarsClusterList {
	if in == nil {
		return nil
	}
	out := new(PolarsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarsClusterSpec) DeepCopyInto(out *PolarsClusterSpec) {
	*out = *in
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(LogLevel)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(RuntimeSpec)
		(*in).DeepCopyInto(*out)
	}
	in.License.DeepCopyInto(&out.License)
	if in.RequireFreeWorkers != nil {
		in, out := &in.RequireFreeWorkers, &out.RequireFreeWorkers
		*out = new(RequireFreeWorkersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AnonymousResults != nil {
		in, out := &in.AnonymousResults, &out.AnonymousResults
		*out = new(AnonymousResultsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Checkpoint != nil {
		in, out := &in.Checkpoint, &out.Checkpoint
		*out = new(CheckpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(LineageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Observatory != nil {
		in, out := &in.Observatory, &out.Observatory
		*out = new(ObservatorySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HostMetrics != nil {
		in, out := &in.HostMetrics, &out.HostMetrics
		*out = new(HostMetricsSpec)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(SchedulerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.WorkerPool.DeepCopyInto(&out.WorkerPool)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarsClusterSpec.
func (in *PolarsClusterSpec) DeepCopy() *PolarsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PolarsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarsClusterStatus) DeepCopyInto(out *PolarsClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Scheduler = in.Scheduler
	out.WorkerPool = in.WorkerPool
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarsClusterStatus.
func (in *PolarsClusterStatus) DeepCopy() *PolarsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PolarsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequireFreeWorkersSpec) DeepCopyInto(out *RequireFreeWorkersSpec) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequireFreeWorkersSpec.
func (in *RequireFreeWorkersSpec) DeepCopy() *RequireFreeWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(RequireFreeWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	in.Composed.DeepCopyInto(&out.Composed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSpec.
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerServicesSpec) DeepCopyInto(out *SchedulerServicesSpec) {
	*out = *in
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Observatory != nil {
		in, out := &in.Observatory, &out.Observatory
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerServicesSpec.
func (in *SchedulerServicesSpec) DeepCopy() *SchedulerServicesSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulerServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerSpec) DeepCopyInto(out *SchedulerSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(SchedulerServicesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerSpec.
func (in *SchedulerSpec) DeepCopy() *SchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerStatus) DeepCopyInto(out *SchedulerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerStatus.
func (in *SchedulerStatus) DeepCopy() *SchedulerStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(v1.ServiceType)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedFilesystemSpec) DeepCopyInto(out *SharedFilesystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedFilesystemSpec.
func (in *SharedFilesystemSpec) DeepCopy() *SharedFilesystemSpec {
	if in == nil {
		return nil
	}
	out := new(SharedFilesystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShuffleDataABSSpec) DeepCopyInto(out *ShuffleDataABSSpec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShuffleDataABSSpec.
func (in *ShuffleDataABSSpec) DeepCopy() *ShuffleDataABSSpec {
	if in == nil {
		return nil
	}
	out := new(ShuffleDataABSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShuffleDataGCSSpec) DeepCopyInto(out *ShuffleDataGCSSpec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShuffleDataGCSSpec.
func (in *ShuffleDataGCSSpec) DeepCopy() *ShuffleDataGCSSpec {
	if in == nil {
		return nil
	}
	out := new(ShuffleDataGCSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShuffleDataS3Spec) DeepCopyInto(out *ShuffleDataS3Spec) {
	*out = *in
	if in.PresignDuration != nil {
		in, out := &in.PresignDuration, &out.PresignDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShuffleDataS3Spec.
func (in *ShuffleDataS3Spec) DeepCopy() *ShuffleDataS3Spec {
	if in == nil {
		return nil
	}
	out := new(ShuffleDataS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShuffleDataSpec) DeepCopyInto(out *ShuffleDataSpec) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalFilesystemSpec)
		**out = **in
	}
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(SharedFilesystemSpec)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ShuffleDataS3Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.ABS != nil {
		in, out := &in.ABS, &out.ABS
		*out = new(ShuffleDataABSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(ShuffleDataGCSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShuffleDataSpec.
func (in *ShuffleDataSpec) DeepCopy() *ShuffleDataSpec {
	if in == nil {
		return nil
	}
	out := new(ShuffleDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	in.OTLPEndpoint.DeepCopyInto(&out.OTLPEndpoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporaryDataSpec) DeepCopyInto(out *TemporaryDataSpec) {
	*out = *in
	if in.EphemeralVolumeClaim != nil {
		in, out := &in.EphemeralVolumeClaim, &out.EphemeralVolumeClaim
		*out = new(EphemeralVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporaryDataSpec.
func (in *TemporaryDataSpec) DeepCopy() *TemporaryDataSpec {
	if in == nil {
		return nil
	}
	out := new(TemporaryDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueOrSource) DeepCopyInto(out *ValueOrSource) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(v1.EnvVarSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueOrSource.
func (in *ValueOrSource) DeepCopy() *ValueOrSource {
	if in == nil {
		return nil
	}
	out := new(ValueOrSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolDeclaration) DeepCopyInto(out *WorkerPoolDeclaration) {
	*out = *in
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HeartBeatInterval != nil {
		in, out := &in.HeartBeatInterval, &out.HeartBeatInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ShuffleData != nil {
		in, out := &in.ShuffleData, &out.ShuffleData
		*out = new(ShuffleDataSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporaryData != nil {
		in, out := &in.TemporaryData, &out.TemporaryData
		*out = new(TemporaryDataSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolDeclaration.
func (in *WorkerPoolDeclaration) DeepCopy() *WorkerPoolDeclaration {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPoolStatus) DeepCopyInto(out *WorkerPoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPoolStatus.
func (in *WorkerPoolStatus) DeepCopy() *WorkerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerPoolStatus)
	in.DeepCopyInto(out)
	return out
}
